"""
model_adapter.py — Local ML model adapter for the UrbanHeat AI simulator.

Team Revenant | SIH 2026 | IHSIH031

WHAT THIS IS
------------
A local adapter that connects the UrbanHeat AI simulator to the
AUTHORITATIVE trained XGBoost model (heat_model.pkl) generated by
ml-modeling/model_pipeline.py.

This adapter expects exactly 7 features:
    ["bldg_area_sqm", "road_length_m", "ndvi", "ndbi", "albedo", "ndwi", "elevation"]
"""

from __future__ import annotations

import os
import sys
from pathlib import Path
from typing import Any, Callable, Dict, Optional, Tuple

import numpy as np
import joblib

# 1. The exact 7 features your pipeline extracts, in this specific order!
FEATURE_ORDER = [
    'bldg_area_sqm', 
    'road_length_m', 
    'ndvi', 
    'ndbi', 
    'albedo', 
    'ndwi', 
    'elevation'
]

def build_predict_fn(
    csv_path: str = "ward1_processed.csv",
    cache_path: str = "",
    refresh_cache: bool = False,
) -> Tuple[Optional[Callable[[np.ndarray], np.ndarray]], Dict[str, Any]]:
    """Build a predict-in-°C callable from the authoritative ML model.

    Returns
    -------
    (predict_fn, info)
        predict_fn : callable mapping X of shape (n, 7) to temperatures in °C.
        info       : dict describing what happened.
    """
    
    # Navigate from simulator-optimizer/ up to the root, then into ml-modeling/
    root_dir = Path(__file__).resolve().parent.parent
    pipeline_model_path = root_dir / "ml-modeling" / "heat_model.pkl"
    
    if not pipeline_model_path.exists():
        msg = f"CRITICAL ERROR: Authoritative model not found at {pipeline_model_path}."
        print(msg)
        return None, {"source": "unavailable", "message": msg}

    try:
        model = joblib.load(pipeline_model_path)
    except Exception as exc:
        msg = f"Failed to load model from {pipeline_model_path}: {exc}"
        print(msg)
        return None, {"source": "unavailable", "message": msg}

    def predict_fn(X: np.ndarray) -> np.ndarray:
        X = np.asarray(X, dtype=float)
        if X.ndim == 1:
            X = X.reshape(1, -1)
        return np.asarray(model.predict(X), dtype=float)

    return predict_fn, {
        "source": "authoritative_artifact",
        "cache_path": str(pipeline_model_path),
        "feature_order": list(FEATURE_ORDER),
        "message": "Successfully loaded authoritative ml-modeling/heat_model.pkl",
    }

# Quick self-test to make sure it finds the model
if __name__ == "__main__":
    print("=== model_adapter self-test ===")
    predict_fn, info = build_predict_fn()
    
    if predict_fn is None:
        print(f"ML adapter unavailable: {info.get('message')}")
        sys.exit(1)
        
    print(info["message"])
    
    try:
        # Create a dummy row of data (1000m2 bldg, 50m road, and 5 dummy indices)
        dummy_X = np.array([[1000.0, 50.0, 0.4, -0.1, 0.15, 0.2, 900.0]])
        pred = predict_fn(dummy_X)
        print(f"SUCCESS: Model loaded and predicted a target temp of {pred[0]:.2f}°C")
    except Exception as e:
        print(f"FAILED during prediction: {e}")